# используем язык java. Travis CI поддерживает другие языки тоже.
language: java
jdk:
  - openjdk11

services:
  - postgresql

before_install:
  - psql -c 'create database tracker;' -U postgres
  - psql -c 'create database spammer;' -U postgres

env:
  global:
    CODECOV_TOKEN="c4e65d1f-03e7-4b27-bd5a-fe7a1756c298"

# используем режим обычного пользователя для сборки проекта.
sudo: false

# после выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# Здесь используется сторонни сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      Meng263@gmail.com
    on_success: never # default: change
    on_failure: always # default: always